name: Lua Translation Utility
description: Manages GitHub issue templates and creates pull requests based on translation strings
branding:
  icon: type
  color: yellow
inputs:
  action:
    description: Which action to run
    required: true
outputs:
  lang:
    description: The language updated from the 'extract' action
runs:
  using: composite
  steps:
    - run: python3 "$GITHUB_ACTION_PATH/action.py" "${{ inputs.action }}"
      shell: bash
